# These are supported funding model platforms

github: nektro
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
custom: https://www.paypal.me/nektro
